### ISSUE TITLE
Is there a versionning mistake ?

### ISSUE THREAD

**Issue by BnitoBzh** [mike-north/ember-intercom-io#175]
The last Release on NPM is 1.0.1
The last tag is 1.1.2
And the package.json version is 0.0.0 ...

Is it possible de clarify this point and publish an up-to-date version ? NPM + Release + package.json ?

**Comment by donaldwasserman** [comment]
So @mike-north just munged some various pull requests along, but I don't know if he cut an NPM release. We should update the package.json with whatever is currently published.

**Comment by mike-north** [comment]
Releases should be cut automatically

* package.json will be set at 0.0.0 because we're now using [semantic-release](https://github.com/semantic-release/semantic-release) which automatically picks a version based on the commit log
* the git tag and npm are out of sync because a recent automated release failed (my github account was rate limited)

I'll create a new patch release for you right now, which should hopefully result in github/npm agreeing on a v1.1.3
