### ISSUE TITLE
Disable widget loading on pages that don't use component

### ISSUE THREAD

**Issue by tmeloliveira** [mike-north/ember-intercom-io#78]
Is there a way to avoid making the requests to `https://widget.intercom.io/widget/` in the pages that I'm not using the add-on?

In my case, I only use intercom for my users that are logged in, so If someone goes to my landing page without being logged in, I do not show the intercom widget. 

I can easily control this by choosing on which route I should place the component `{{intercom-io}}`. But, even though the widget is not showing, I can still see the requests in the network tab, which represents around 250Kb of JS (gzipped). 

It would be great if I could reduce this size, and only make the requests for the pages that actually need it. 

Thanks in advance!

**Comment by xtagon** [comment]
Was this issue closed because it was implemented, or is it a wont-fix?

**Comment by donaldwasserman** [comment]
Sorry, @xtagon I should have clarified a bit more and thought this was more of a stale issue.

There's not a way to separate out what intercom chooses to load via their script tag generally speaking. So if the issue is to prevent the extra data from loading, I think an app would have to create the script tag and handle inserting it dynamically [see.](https://github.com/mike-north/ember-intercom-io/blob/master/client/intercom-shim.js)

This addon really can't handle that, because it depends on having the intercom "module" available all over the place.

I'd be happy to talk more about this issue, but it's hard to figure out what the right path forward on this (especially because the js is loaded async and this is a pretty standard way things like segment etc work)

**Comment by xtagon** [comment]
Thank you for clarifying, that makes sense. Probably not worth the effort then (for me) but I was just curious if it was possible.
